services:
- type: web
name: piazza
env: ruby
plan: free
numInstances: 1
buildCommand: ./bin/render-build.sh
startCommand: bundle exec puma -C config/deploy/puma.rb
envVars:
- key: DATABASE_URL
fromDatabase:
name: piazza-db
property: connectionString
- key: a1f52a22b87c14b47944b53707c76c1c
sync: false
databases:
- name: piazza-db
plan: free
postgresMajorVersion: 14